version: '3.1'

services:
  app:
    container_name: <%= dir %>-app
    image: wordpress:php7.1-apache
    depends_on:
      - mysql
    ports:
      - 8000:80
    volumes:
      - ./<%= dir %>:/var/www/html/wp-content/themes/<%= dir %>
      - ./wp:/var/www/html/
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    entrypoint: apache2-foreground

  mysql:
    container_name: <%= dir %>-mysql
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/local:/database/local
      - ./database/wordpress.sql:/wordpress.sql
      - ./database/migrate.txt:/migrate.txt
