version: '2'

services:
  app:
    container_name: <%= dir %>-app
    build: .
    links:
      - mysql
    ports:
      - 8000:80
    environment:
      TYPO3_CONTEXT: Development
    volumes:
      - ./<%= dir %>/:/var/www/html/typo3/typo3conf/ext/<%= dir %>/
      - ./typo3/composer.json:/var/www/html/typo3/composer.json
      - ./:/var/www/html/

  mysql:
    container_name: <%= dir %>-mysql
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/local:/database/local
      - ./database/typo3.sql:/typo3.sql
